---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-ingest
  labels:
    app: elasticsearch
    role: ingest
data:
  elasticsearch.yml: |-
    cluster.name: ${CLUSTER_NAME}
    node.name: ${NODE_NAME}
    discovery.seed_hosts: ${NODE_LIST}
    cluster.initial_master_nodes: ${MASTER_NODES}

    network.host: 0.0.0.0

    node.roles: [ ingest ]

    bootstrap.memory_lock: false
    xpack.license.self_generated.type: trial
    xpack.security.enabled: true
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-ingest
  labels:
    app: elasticsearch
    role: ingest
spec:
  selector:
    app: elasticsearch
    role: ingest
  ports:
  - port: 9300
    name: transport
  - port: 9200
    name: ingest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-ingest
  labels:
    app: elasticsearch
    role: ingest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
      role: ingest
  template:
    metadata:
      labels:
        app: elasticsearch
        role: ingest
    spec:
      containers:
      - name: elasticsearch-ingest
        image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
        env:
        - name: CLUSTER_NAME
          value: elasticsearch
        - name: NODE_NAME
          value: elasticsearch-ingest
        - name: NODE_LIST
          value: elasticsearch-master,elasticsearch-data,elasticsearch-ingest
        - name: MASTER_NODES
          value: elasticsearch-master
        - name: "ES_JAVA_OPTS"
          value: "-Xms512m -Xmx512m"
        ports:
        - containerPort: 9200
          name: ingest
        - containerPort: 9300
          name: transport
        volumeMounts:
          - name: config
            mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
            readOnly: true
            subPath: elasticsearch.yml
          - name: storage
            mountPath: /data
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1500m"
      volumes:
      - name: config
        configMap:
          name: elasticsearch-ingest
      - name: "storage"
        emptyDir:
          medium: ""
      initContainers:
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true