---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-ingest
  labels:
    app: elasticsearch
    role: ingest
data:
  elasticsearch.yml: |-
    cluster.name: ${CLUSTER_NAME}
    ingest.geoip.downloader.enabled: false
    node.name: ${NODE_NAME}
    discovery.seed_hosts: ${NODE_LIST}
    cluster.initial_master_nodes: ${MASTER_NODES}
    bootstrap.memory_lock: ${MEMORY_LOCK}
    network.host: 0.0.0.0
    node.roles: [ ingest ]
    xpack.license.self_generated.type: trial
    xpack.security.enabled: true
  limits.conf: |-
    elasticsearch soft memlock unlimited
    elasticsearch hard memlock unlimited
    elasticsearch hard nofile 65536
    elasticsearch soft nofile 65536
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-ingest
  labels:
    app: elasticsearch
    role: ingest
spec:
  selector:
    app: elasticsearch
    role: ingest
  ports:
  - port: 9300
    name: transport
  - port: 9200
    name: ingest
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic-ingest
  labels:
    app: elasticsearch
    role: ingest
spec:
  selector:
    matchLabels:
      app: elasticsearch
      role: ingest
  serviceName: elasticsearch-ingest
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
        role: ingest
    spec:
      containers:
      - name: elasticsearch-ingest
        image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
        env:
        - name: CLUSTER_NAME
          value: elasticsearch
        - name: NODE_NAME
          value: elasticsearch-ingest
        - name: NODE_LIST
          value: elasticsearch-master,elasticsearch-data,elasticsearch-ingest
        - name: MASTER_NODES
          value: elasticsearch-master
        - name: "ES_JAVA_OPTS"
          value: "-Xms512m -Xmx512m"
        - name: "MEMORY_LOCK"
          value: "false"
        ports:
        - containerPort: 9200
          name: ingest
        - containerPort: 9300
          name: transport
        volumeMounts:
          - name: config
            mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
            readOnly: true
            subPath: elasticsearch.yml
          - name: limits
            mountPath: /etc/security/limits.conf
            readOnly: true
            subPath: limits.conf
          - name: elastic-ingest
            mountPath: /usr/share/elasticsearch/data
        resources:
          limits:
            memory: "3072Mi"
            cpu: "2000m"
      volumes:
      - name: config
        configMap:
          name: elasticsearch-ingest
      - name: limits
        configMap:
          name: elasticsearch-ingest
      initContainers:
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: fix-permissions1
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: elastic-ingest
          mountPath: /usr/share/elasticsearch/data
      - name: fix-permissions2
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /tmp"]
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: elastic-ingest
      labels:
        app: elasticsearch
        role: ingest
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: rook-ceph-block
      resources:
        requests:
          storage: 10Gi
