apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elastic-ingress
  labels:
    app: elastic-ingapp
spec:
  rules:
  - host: ux360.izzi.mx
    http:
      paths:
      - pathType: Prefix
        path: "/elastic"
        backend:
          service:
            name: elasticsearch-ingest
            port: 
              number: 9200
